### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by XinYenFon** [margarett/SimpleDesk_SMF2.1#1]
I see the toggle image is missing. I suggest converting current toggle into SMF 2.1's default.

**Comment by margarett** [comment]
What's the toggle image? :tongue:

**Comment by XinYenFon** [comment]
Actually @live627 can explain this way better since he worked on that. Actually @Arantor was the father of that (AFAIK) but since he's way too busy, I don't think he'll help us on this quest :)

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/images/toggle.png

**Comment by margarett** [comment]
I think that you are referring to the "expand" image? I think that's what kindred was referring to (as it was missing)
Looking at SMF's BoardIndex.template.php, it seems this thing here

```
<span id="category_', $category['id'], '_upshrink" class="', $category['is_collapsed'] ? 'toggle_down' : 'toggle_up', ' floatright" data-collapsed="', (int) $category['is_collapsed'], '" title="', !$category['is_collapsed'] ? $txt['hide_category'] : $txt['show_category'] ,'" style="display: none;"></span>';
```

I can look at this. Or is it something that you want do do as it's template stuff?

**Comment by XinYenFon** [comment]
That's really something I want to stay away from :D (it involves JS).
